### ISSUE TITLE
Uncaught TypeError: Path must be a string. Received undefined.

### ISSUE THREAD

**Issue by habro** [fentas/atom-to-base64#3]
When more than a single character is highlighted and you right click -> base64 -> insert it gives the error listed in the subject. It freezes Atom (1.7.4) using to-base64(0.4.2).so I can't get the stack trace.

**Comment by fentas** [comment]
Hey, thanks for reporting. Will look into it asap. :+1:

**Comment by fentas** [comment]
Hey,
sorry took a while longer then anticipated.
Plz try v0.5.0.

If not fixed, plz reopen.
